config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "topics#index"

  resources :users do 
    resources :friendships , :controller => "user_friendships" do
      collection do 
        get :friend_request
        get :friendship
        post :invite_friendship
        post :accept_friendship
        post :refuse_friendship
      end
    end
    resources :favorites , :controller => "user_favorites"
  	resources :topics
    collection do
        get :favorite
        get :like
        get :draft
        patch :update_draft
        get :profile , param: :useremail # XXX
    end
  end

  resources :topics do
  	resources :comments , :controller => "topic_comments"
  	collection do
      get :about 
    end

    member do 
      post :favorite
      post :like
      post :subscribe
      post :create_tag
    end
  end

  namespace :admin do
    resources :topics 
    resources :users
    resources :categories
  end

  namespace :api , path: '' do
    # constraints(host: 'api-example.com') do

    # end
  end


  namespace :api do
    resources :users
    get '*unmatched_route', to: 'base#page_404'
  end

  namespace :test do
    resources :users
    get '*unmatched_route', to: 'base#page_404'
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :content , :counter_cache => true

	belongs_to :user
	belongs_to :limit
	has_many :comments , :dependent => :destroy
	has_many :category_topicships , :dependent => :destroy
	has_many :categories , :through => :category_topicships , :dependent => :destroy
	has_many :favorites , :dependent => :destroy
	has_many :favorited_users , :through => :favorites , :source => :user
	has_many :likes , :dependent => :destroy
	has_many :liked_users , :through => :likes , :source => :user
	has_many :subscribes , :dependent => :destroy
	has_many :subscribed_users , :through => :subscribes , :source => :user
	has_many :tag_topicships , :dependent => :destroy
	has_many :tags , :through => :tag_topicships , :dependent => :destroy
	has_many :images , :dependent => :destroy

	delegate :id , :to => :categories , :prefix => true , :allow_nil => true
	
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
	before_action :authenticate_user! 
	before_action :authenticate_admin
	before_action :find_user
	
	def index

		case params[:order]
		when "Update"
			sort_by = "comments.created_at DESC"
		when "Reply"
			sort_by = "comments_count DESC"
		when "Views"
			sort_by = "views_count DESC"
		when "created_at"
		end
		
		@topics = Topic.includes(:comments , :user).where( :draft => false ).order(sort_by).page(params[:page]).per(15)
		
		if params[:keyword] 
			@search_by = params[:keyword]
			@topics = Topic.includes(:comments , :user , :categories).where( :draft => false ).where( "categories.id" => @search_by ).order(sort_by).page(params[:page]).per(15)
		end

	end

	def destroy
		@topic = Topic.find(params[:id])
		@topic.destroy
		flash[:alert] = "successfully deleted"
		redirect_to topics_path
	end

	
	protected

	def find_user
		@user = current_user
	end

	def wirte_topic
		params.require(:topic).permit(:title , :content , :user_id , :comments_count , :views_count , :draft , :category_ids => [] )
	end

	def authenticate_admin
		unless current_user.admin?
		flash[:alert] = "Not allow!"
		redirect_to topics_path
		end
	end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_action :find_user
	before_action :find_topic , :except => [:index , :new , :create , :about ]
	
	def index
		
		#@topic.draft_time > Time.zone.now
		@topics = Topic.all
		@topics_draft = Topic.where(:draft => true)
		@topics_draft.each do |draft|
			if Time.now > draft.draft_time 
				draft.update(:draft => false)
			end
		end

		@categories = Category.all

		case params[:order]
			when "Update"
				sort_by = "comments.created_at DESC"
			when "Reply"
				sort_by = "comments_count DESC"
			when "Views"
				sort_by = "views_count DESC"
			when "created_at"
		end
		
		@topics = Topic.includes(:comments , :user).where( :draft => false ).order(sort_by).page(params[:page]).per(15)
		
		if params[:keyword] 
			@keyword_by = params[:keyword]
			@topics = Topic.includes(:comments , :user , :categories).where( :draft => false ).where( "categories.id" => @keyword_by ).order(sort_by).page(params[:page]).per(15)
		end

		if params[:search]
			@search_by = params[:search]
			@topics = Topic.includes(:tags).where("tags.name" => @search_by).page(params[:page]).per(15)
		end
		#@topics = Topic.where('id = 1').or(Topic.where(:user_id => "3")).page(params[:page]).per(15)
	end

	def show 
		limit(@topic.limit_id)
		views = 2 + @topic.views_count
		@topic.update(:views_count => views)
		@images = Image.where(:topic_id => @topic.id)
		@comment = @topic.comments.build
		@comments = @topic.comments.where(:draft => false)
		@favorite_users = @topic.liked_users
		@favorite = @user.favorites.build
		@tag = Tag.new
		@tags = Tag.all
	end

	def new
		authenticate_user!
		@topic = @user.topics.build
	end

	def create
		@tag = params['topic']['content'].split(/#/)
		params['topic']['content'] = @tag.shift
		@topic = @user.topics.build(wirte_topic)
		if @topic.save
			if params['images']
				params['images'].each do |image|
					@topic.images.create(image: image)
				end
			end

			@tag.each do |s|
				@c_tag = Tag.create(:name => s.rstrip)
				@topic.tag_topicships.create(:tag_id => @c_tag.id)
			end
			flash[:notice] = "added successfully"
			redirect_to topics_path
		else
			render "new"
		end
	end

	def edit
		
	end

	def update
		if @topic.update(wirte_topic)
			flash[:notice] = "update completed"
			redirect_to topic_path(@topic)
		else
			render "edit"
		end
	end

	def destroy
		@topic.destroy
		flash[:alert] = "successfully deleted"
		redirect_to topics_path
	end

	def about
		@users_count = User.all.size
		@topics_count = Topic.all.size
		@comments_count = Comment.all.size
	end

	def favorite
		@favorite = current_user.favorites.find_by_topic_id(@topic)
		if current_user.favorited_topics.include?(@topic)
			@favorite.destroy
		else
			Favorite.create( :topic => @topic , :user => current_user)
		end

		respond_to do |format|
			format.js
		end
	end

	def like
		if current_user.liked_topics.include?(@topic)
			current_user.liked_topics.delete(@topic)
		else
			Like.create!( :topic => @topic, :user => current_user )
		end
		@topic.reload
		respond_to do |format|
			format.js
		end
	end

	def subscribe
		if current_user.subscribed_topics.include?(@topic)
			current_user.subscribed_topics.delete(@topic)
		else
			Subscribe.create!(:topic => @topic , :user => current_user)
		end

		respond_to do |format|
			format.js
		end
	end

	def create_tag
		@tag = Tag.new(params.require(:tag).permit(:name))
		if @tag.save
			flash[:noitce] = "Tag Created"
			redirect_to topic_path(@topic)
		else
			flash[:alert] = "error"
			render "show"
		end
	end

	
	private

	def find_user
		@user = current_user
	end

	def find_topic
		@topic = Topic.find(params[:id])
	end

	def wirte_topic
		params.require(:topic).permit(:title , :content , :user_id , :comments_count , :views_count , :draft , :draft_time , :limit_id , { :category_ids => [] } , { :tag_ids => [] } )
	end

	def limit(id)
		case id
			when 1
				if current_user != @topic.user
					flash[:alert] = "You do not have permission"
					redirect_to :back
				end
			when 2
				if current_user != @topic.user
					if !(current_user.friendships.find_by_friend_id(@topic.user.id) && current_user.inverse_friendships.find_by_user_id(@topic.user.id))
						flash[:alert] = "Add me as a friend if you want to see it! ! ! ! ! ! ! ! ! ! !"
						redirect_to :back
					end
				end
		end
	end

end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_comment_form.html.erb
<% if @comment.errors.any? %>
	<ul>
		<% @comment.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<div class="form-group">
	<%= f.file_field :avatar %>
</div>
<div class="form-group">
	<%= f.label :draft , "Draft" %>
	<%= f.check_box :draft, {}, "true" , "false" %>
</div>
<div class="form-group">
<%= f.label :content , "Content : " %>
<%= f.text_area :content , :rows => "10" , :class => "form-control" %>
</div>
<%= f.hidden_field :user_id , :value => @user.id %>

<br>
<%= f.submit :class => "btn btn-success" %>

app/views/topics/_current_control.html.erb
<div class="col-md-4 text-center">
	<% if current_user.favorited_topics.include?(@topic) %>
		<%= button_to "Delete My Favorites" , favorite_topic_path(@topic) , :remote => true , :id => "favorite" , :class => "btn btn-primary" %>
	<% else %>
		<%= button_to "Add My Favorites" , favorite_topic_path(@topic) , :remote => true , :id => "favorite" , :class => "btn btn-primary"  %>
	<% end %>
</div>

<div class="col-md-4 text-center">
	<% if current_user.subscribed_topics.include?(@topic) %>
		<%= button_to "UnSubscribe" , subscribe_topic_path(@topic) , :remote => true , :id => "subscribe" , :class => "btn btn-warning" %>
	<% else %>
		<%= button_to "Subscribe" , subscribe_topic_path(@topic) , :remote => true , :id => "subscribe" , :class => "btn btn-warning" %>
	<% end %>
</div>
		
	<div class="col-md-4 text-center">
		<% if current_user.liked_topics.include?(@topic) %>
		<div class="like_button">
				<%= button_to like_topic_path(@topic) , :remote => true , :id => "like" , :class => "btn btn-info" do %>Unlike
				<span class="badge"><%= @topic.likes_count %></span>
			<% end %>
		</div>
		
	<% else %>
		<div class="like_button">
			<%= button_to like_topic_path(@topic) , :remote => true , :id => "like" , :class => "btn btn-info" do %>Like 				<span class="badge"><%= @topic.likes_count %></span>
			<% end %>
		</div>
	<% end %>
	</div>
	
<br><br>

<div class="tag">
	<div class="form-group tag-top">
		<%= form_for @tag , :url => create_tag_topic_path(@topic , @tag) do |f| %>
			<%= f.text_field :name %>
			<%= f.submit :class => "btn btn-success" %>
		<% end %>
	</div>

	<%= form_for @topic , :url => topic_path(@topic) , :method => :patch do |f| %>
		<div class="form-group">
			<%= f.collection_check_boxes(:tag_ids , Tag.all , :id , :name) %>
		</div>
		<%= f.submit "Add Tags" , :class => "btn btn-success pull-right" %>
	<% end %>
</div>

app/views/topics/_form.html.erb
<% if @topic.errors.any? %>
	<ul>
		<% @topic.errors.full_messages.each do |msg| %>
			<li><%= msg %></li> 
		<% end %>
	</ul>
<% end %>

<div class="form-group">

	<div class="file-field">
		<%= file_field_tag "images[]" , :type => :file %>
	</div>
	<br>
	<span id="new_file" class="btn btn-warning">More File</span>
</div>
<div class="form-group">
	<%= f.label :draft do %>Draft
	<%= f.check_box :draft, {}, 'true' , 'false' %>
	<% end %>
</div>
<div id="draft-time" class="form-group">
	<%= f.datetime_field :draft_time %>
</div>
<div class="form-group">
	<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
</div>
<div class="form-group">
	<%= f.label :title , "Title : " %>
	<%= f.text_field :title , :class => "form-control" %>
</div>
	<%= f.label :content , "Content : " %>
	<%= f.text_area :content , :rows => "20" , :class => "form-control" %>
<div class="form-group">
	<%= f.hidden_field :user_id , :value => @user.id %>
</div>
	<%= f.submit :class => "btn btn-success" %> 


<script>
	$(document).ready(function(){
		$('#new_file').click(function(){
			$('.file-field').append('<%= file_field_tag "images[]" , :type => :file %>');
		});

		$("#topic_draft").click(function(){
			$("#draft-time").toggleClass('show')
		});
	});	
</script>

app/views/topics/about.html.erb
<div class="container text-center">
	<h1>Welcome To Forum</h1>

	<h3>We have <%= @users_count %> users</h3>	
	<h3>There are <%= @topics_count %> Topics</h3>
	<h3>And <%= @comments_count %> comments</h3>

	<h2>Come And Join Us</h2>

</div>

app/views/topics/edit.html.erb
<div class="container">
	<h2><%= @topic.user.email %></h2>
	<p><%= @topic.created_at %></p>
	<div class="form-group">
		<%= form_for @topic , :url => topic_path(@topic) , :html => { :multipart => true } , :method => :patch do |f| %>
			<%= render :partial => "form" , :locals => {:f => f} %>
			<%= link_to "Cancel" , topic_path(@topic) , :class => "btn btn-primary pull-right" %>
		<% end %>
	</div>
</div>

app/views/topics/favorite.js.erb
<% if current_user.favorited_topics.include?(@topic) %>
	<% value = "Delete My Faovrites" %>
<% else %>
	<% value = "Add My Favorites" %>
<% end %>

$("#favorite[type=submit]").val("<%= value %>")

app/views/topics/hello.html.erb
<div id="app-1">
  {{ message }}
</div>

<div id="app-2">
  <span v-bind:title="message">
    Hover your mouse over me for a few seconds to see my dynamically bound title!
  </span>
</div>

<div id="app-3">
  <p v-if="seen">Now you see me</p>
</div>

<div id="app-4">
  <ol>
    <li v-for="todo in todos">
      {{ todo.text }}
    </li>
  </ol>
</div>

<div id="app-5">
  <p>{{ message }}</p>
  <button v-on:click="reverseMessage">Reverse Message</button>
</div>

<div id="app-6">
  <p>{{ message }}</p>
  <input v-model="message">
</div>


<script>
	var app = new Vue({
		el: '#app-1',
		data: {
			message: "hello Vue!"
		}
	})

	var app2 = new Vue({
		el: '#app-2',
		data: {
			message: 'You loaded this page on ' + new Date()
		}
	})

	var app3 = new Vue({
		el: '#app-3',
		data: {
			seen: true
		}
	})

	var app4 = new Vue({
	  el: '#app-4',
	  data: {
	    todos: [
	      { text: 'Learn JavaScript' },
	      { text: 'Learn Vue' },
	      { text: 'Build something awesome' }
	    ]
	  }
	})

	var app5 = new Vue({
	  el: '#app-5',
	  data: {
	    message: 'Hello Vue.js!'
	  },
	  methods: {
	    reverseMessage: function () {
	      this.message = this.message.split('').reverse().join('')
	    }
	  }
	})

	var app6 = new Vue({
	  el: '#app-6',
	  data: {
	    message: 'Hello Vue!'
	  }
	})
	



</script>

app/views/topics/index.html.erb
<div class="container">
	<% if @user.try(:role) == "admin" %>
		<%= link_to "Back" , admin_topics_path , :class => "btn btn-danger btn-lg pull-right" %>
	<% end %>
	<h1>Forum</h1>
	
	<%= form_tag topics_path , :method => :get do %>
		<%= text_field_tag "search" , nil , size: 50 %>
		<%= submit_tag "Search Tag" , :class => "btn btn-info" %>
		<%= link_to "About" , about_topics_path , :class => "btn btn-default pull-right" %>
	<% end %>

	<div class="check_box">
		<% @categories.each do |c| %>
			<%= link_to c.name , topics_path(:keyword => c) , :class => "btn btn-warning" %>
		<% end %>
		<%= link_to "Default" , topics_path , :class => "btn btn-warning" %>
	</div>
	<br>
	<div class="sort">
		<%= link_to "Sort by last Reply" , topics_path( :order => "Update" , :keyword => @search_by ) , :class => "btn btn-primary" %>
		<%= link_to "Sort by Count of Reply" , topics_path( :order => "Reply" , :keyword => @search_by ) , :class => "btn btn-primary" %>
		<%= link_to "Sort by Count of Views" , topics_path( :order => "Views" , :keyword => @search_by ) , :class => "btn btn-primary" %>
		<%= link_to "Sort by Default" , topics_path(:keyword => @search_by ) , :class => "btn btn-primary" %>
	</div>
	<br>
	<%= link_to "New" , new_topic_path , :class => "btn btn-success btn-lg" %>
	<br>
	<%= paginate @topics %>
	

	<table class="table table-striped">
		<tr>
			<th>subject</th>
			<th>Writer</th>
			<th>Coverer</th>
			<th>Last turnover time</th>
			<th>Overturn</th>
			<th>viewing count</th>
		</tr>
		
		<% @topics.each do |t| %>
			<%# users = t.comments.includes(:user).pluck("user_id").uniq%>
			<% comment_users = [] %>
			<% t.comments.each do |comments| %>
				<% comment_users.push(comments.user.email) %>
			<% end %>
			<% comment_users.uniq! %>
			
			<tr>
				<td><%= link_to t.title , topic_path(t) %></td>
				<td><%= link_to t.user.email , user_path(t.user) %></td>
				<td>
					<% comment_users.each do |user| %>
						<%= user %>
					<% end %>
				</td>
				<% if params.try(:order) == 'Update' %>
					<td><%= t.comments.last.try(:created_at) %></td>
				<% else %>
					<td><%= t.comments.first.try(:created_at) %></td>
				<% end %>
				<td><%= t.comments_count %></td>
				<td><%= t.views_count %></td>
			</tr>
		<% end %>
	</table>
</div>
	

app/views/topics/like.js.erb
<% count = @topic.likes_count %>
<% if current_user.liked_topics.include?(@topic) %>
	<% value = "Unlike" %>
<% else %>
	<% value = "Like" %>
<% end %>

$("#like").html("<%= value %> <span class='badge'><%= @topic.likes_count %></span>")


// turbolinks => false

app/views/topics/new.html.erb
<div class="container">
	<h1>New Topic</h1>
	
	<h2><%= @topic.user.email %></h2>
	<p><%= @topic.created_at %></p>
	
	<%= form_for @topic , :url => topics_path(@topic) , :html => { :multipart => true } do |f| %>
		<%= render :partial => "form" , :locals => {:f => f} %>
	<% end %>
</div>

app/views/topics/show.html.erb
<div id="topic_index" class="container">
	<br>
	<%= link_to "Back To List" , topics_path , :class => "btn btn-primary pull-right" %>
	<br><br>

	<% if current_user %>
		<%= render :partial => "current_control" %>
	<% end %>
	<br>	
	<div class="users">
		<h3 class="text-center">Followed users</h3>
		<% @favorite_users.each do |user| %>
			<%= user.email %> <p>	</p>
		<% end %>
	</div>

	<% if @topic.limit.id != 3 %>
		<%= form_for @comment , :url => topic_comments_path(@topic , @comment) , :remote => true do |f| %>
			<%= render :partial => "comment_form" , :locals => {:f => f} %>
		<% end %>
	<% end %>

	<div class="clearfix"></div>
		<%= form_for @topic do |f|  %>
			<div class="btn">
				<% if current_user == @topic.user %>
					<%= link_to "Delete" , topic_path(@topic) , :method => :delete , :class => "btn btn-danger" %>
					<%= link_to "Edit" , edit_topic_path(@topic) , :class => "btn btn-success" %>
				<% end %>
			</div>

			<div class="images text-center">
				<% @images.each do |image| %>
					<%= image_tag image.image.url(:medium) %>
				<% end %>
			</div>

			<div class="form-group">
			<%= f.label :title , "Title : " %>
			<%= f.text_field :title ,  :disabled => "disabled" , :class => "form-control" %>
			</div>
			<div class="form-group">
			<h3><%= @topic.user.email %></h3>
			<p><%= @topic.created_at %></p>
			</div>
			<div class="form-group">
			<%= f.label :content , "Content : " %>
			<%= f.text_area :content , :rows => "20" , :disabled => "disabled" , :class => "form-control" %>
			</div>
		<% end %>


	<div class="form-group">
		<% @comments.each do |c| %>
			<%= form_for c , :url => "" do |f| %>
				<% if c.user == current_user %>
					<%= link_to "Edit" , edit_topic_comment_path(@topic , c) , :class => "btn btn-success" %>
					<%= link_to "Delete" , topic_comment_path(@topic , c) , :method => :delete , :class => "btn btn-danger" , :remote => true %>
				<% end %>
				<h2>Reply : </h2>
					<% if c.avatar.url != "/images/original/missing.png" %>
					<div class="form-group text-center">
						<%= image_tag c.avatar.url %>
					</div>
				<% end %>
				<h3><%= c.user.email %></h3>
				<p><%= c.created_at %></p>
				<%= f.label :content , "Content : " %>
				<%= f.text_area :content , :rows => "20" , :disabled => "disabled" , :class => "form-control" %>
			<% end %>
		<% end %>
	</div>

	
</div>
	

app/views/topics/subscribe.js.erb
<% if current_user.subscribed_topics.include?(@topic) %>
	<% value = "UnSubscribe" %>
<% else %>
	<% value = "Subscribe" %>
<% end %>

$("#subscribe").val("<%= value %>")