config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "topics#index"

  resources :users do 
    resources :friendships , :controller => "user_friendships" do
      collection do 
        get :friend_request
        get :friendship
        post :invite_friendship
        post :accept_friendship
        post :refuse_friendship
      end
    end
    resources :favorites , :controller => "user_favorites"
  	resources :topics
    collection do
        get :favorite
        get :like
        get :draft
        patch :update_draft
        get :profile , param: :useremail # XXX
    end
  end

  resources :topics do
  	resources :comments , :controller => "topic_comments"
  	collection do
      get :about 
    end

    member do 
      post :favorite
      post :like
      post :subscribe
      post :create_tag
    end
  end

  namespace :admin do
    resources :topics 
    resources :users
    resources :categories
  end

  namespace :api , path: '' do
    # constraints(host: 'api-example.com') do

    # end
  end


  namespace :api do
    resources :users
    get '*unmatched_route', to: 'base#page_404'
  end

  namespace :test do
    resources :users
    get '*unmatched_route', to: 'base#page_404'
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :content , :counter_cache => true

	belongs_to :user
	belongs_to :limit
	has_many :comments , :dependent => :destroy
	has_many :category_topicships , :dependent => :destroy
	has_many :categories , :through => :category_topicships , :dependent => :destroy
	has_many :favorites , :dependent => :destroy
	has_many :favorited_users , :through => :favorites , :source => :user
	has_many :likes , :dependent => :destroy
	has_many :liked_users , :through => :likes , :source => :user
	has_many :subscribes , :dependent => :destroy
	has_many :subscribed_users , :through => :subscribes , :source => :user
	has_many :tag_topicships , :dependent => :destroy
	has_many :tags , :through => :tag_topicships , :dependent => :destroy
	has_many :images , :dependent => :destroy

	delegate :id , :to => :categories , :prefix => true , :allow_nil => true
	
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	def admin?
	self.role == "admin"
	end
	
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

	has_many :topics , :dependent => :destroy
	has_many :comments , :dependent => :destroy
	has_many :favorites , :dependent => :destroy
	has_many :favorited_topics , :through => :favorites , :source => :topic
	has_many :likes , :dependent => :destroy
	has_many :liked_topics , :through => :likes , :source => :topic
	has_many :subscribes , :dependent => :destroy
	has_many :subscribed_topics , :through => :subscribes , :source => :topic
	has_many :friendships , :dependent => :destroy
	has_many :friends, :through => :friendships , :dependent => :destroy
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user


	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  	def get_fb_data
 		j = RestClient.get "https://graph.facebook.com/v2.5/me", :params => { :access_token => self.fb_token, :fields => "id,name,email,picture" }
 		JSON.parse(j)
	end

	def self.from_omniauth(auth)
	     # Case 1: Find existing user by facebook uid
	     user = User.find_by_fb_uid( auth.uid )
	     if user
	        user.fb_token = auth.credentials.token
	        user.avatar_file_name = auth.info.image
	        #user.fb_raw_data = auth
	        user.save!
	       return user
	     end

	     # Case 2: Find existing user by email
	     existing_user = User.find_by_email( auth.info.email )
	     if existing_user
	       existing_user.fb_uid = auth.uid
	       existing_user.fb_token = auth.credentials.token
	       existing_user.avatar_file_name = auth.info.image
	       #existing_user.fb_raw_data = auth
	       existing_user.save!
	       return existing_user
	     end

	     # Case 3: Create new password
	     user = User.new
	     user.fb_uid = auth.uid
	     user.fb_token = auth.credentials.token
	     user.avatar_file_name = auth.info.image
	     user.email = auth.info.email
	     user.password = Devise.friendly_token[0,20]
	     #user.fb_raw_data = auth
	     user.save!
	     return user
	end
    # def avatar_content_type
    #     if avatar_content_type.present?
    #       avatar_content_type.url
    #     else
    #       '/default-avatar.png'
    #     end
	# end
	# def avatar_file_name
    #     if avatar_file_name.present?
    #       avatar_file_name.url
    #     else
    #       '/default-avatar.png'
    #     end
    # end
	# def avatar_file_size
    #     if avatar_file_size.present?
    #       avatar_file_size.url
    #     else
    #       '/default-avatar.png'
    #     end
	# end
	# def avatar_updated_at
    #     if avatar_updated_at.present?
    #       avatar_updated_at.url
    #     else
    #       '/default-avatar.png'
    #     end
    # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

	before_action :authenticate_user! #Crawl individual devise Providing method, required entry
	before_action :authenticate_admin # Re-introduction
	
	def index
		@users = User.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(write_user)
			flash[:notice] = "OOOO"
			redirect_to admin_users_path
		else	
			render "edit"
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:alert] = "XXX"
		redirect_to admin_users_path
		
	end



	protected

	def write_user
		params.require(:user).permit(:nickname , :role)
	end

	def authenticate_admin
		unless current_user.admin?
		flash[:alert] = "Not allow!"
		redirect_to topics_path
		end
	end

end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
	#$.get('http://localhost:3000/api/users.json', null, function(data) { console.log(data); });
	# $.ajax({
	#   url: "http://api.localhost:3000/api/users/3.json",
	#   method: "POST",
	#   success: function(data) { console.log(data) }
	# })


	def index
		@users = User.all
		render json: { users: @users }
	end

	def show 
		#response.headers['Content-Type'] = "HTML"
		@user = User.find(params[:id])
		render json: { user: @user } #, status: 40
	end

	def create
		@user = User.all
		render json: { user: @user } #, status: 40
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.where.not(:id => current_user)
	end

	def show
		@user = User.find(params[:id])
	end
	def create
		
	end

	def update 
		@user = current_user
		if @user.update(write_user)
			flash[:notice] = "Update!!!"
			redirect_to profile_users_path(:useremail => current_user.email)
		else
			flash[:alert] = "Error!!!"
			render "profile"
		end
	end

	def profile
		@user = User.find_by(email: params[:useremail])
		@topics = @user.topics
		@comments = @user.comments
	end

	def favorite
		@user = current_user
		@favorites = @user.favorites
	end

	def draft
		@user = current_user
		@topics = @user.topics.where( :draft => true)
		@comments = @user.comments.where( :draft => true)
	end

	def update_draft
		@topic = Topic.find(params[:topic_id])
		if @topic.update(params.require(:topic).permit(:draft , :title , :content))
			flash[:notice] = "Update!!!"
			redirect_to draft_users_path
		else
			flash[:alert] = "No!!!"
			render "draft"
		end
	end

	def like
		@user = current_user
		@likes = @user.likes
	end

	# def favorite
	# 	@user = current_user
	# 	@favorite = Favorite.where( :user_id => @user.id )
	# end

	def write_user
		params.require(:user).permit(:nickname , :avatar)
	end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/draft.html.erb
<div class="container">
	<h2>Darft</h2>

	<h3>Topics :</h3>
	<% @topics.each do |t| %>
		<%= form_for t , :url => update_draft_users_path(:topic_id => t.id ) , :method => :patch do |f| %>
			<div class="form-group">
				<%= f.label :draft , "Draft" %>
				<%= f.check_box :draft, {}, 'true' , 'false' %>
			</div>
			<div class="form-group">
				<%= f.label :title , "Title : " %>
				<%= f.text_field :title , :class => "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :content , "Content : " %>
				<%= f.text_area :content , :rows => "15" , :class => "form-control" %>
			</div>
			<%= f.submit :class => "btn btn-success" %>
		<% end %>
	<% end %>

</div>
	

app/views/users/favorite.html.erb
<div class="container">
	<h2>My Favorites</h2>
	
	<%= link_to "Back Profile" , profile_users_path , :class => "btn btn-primary pull-right" %> 
	<br>
	<br>
	<% @favorites.each do |favorite| %>
		<%= form_for favorite.topic , :url => "" do |f| %>
			<%= f.label :title , "Title : " %>
			<%= f.text_field :title , :disabled => "disabled" , :class => "form-control" %>
			<%= f.label :content , "Content : " %>
			<%= f.text_area :content , :rows => "20" , :disabled => "disabled" , :class => "form-control" %>
		<% end %> 
	<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	
	<h1>Users</h1>

	<table class="table table-striped">
		<tr>
			<th>email</th>
			<th>Add Friend</th>
		</tr>
		
		<% @users.each do |user| %>
			<tr>
				<td><%= link_to user.email , user_path(user) %></td>
				<% if current_user.friends.include?(user) %>
					<td><%= button_to "Uninvite Friend" , invite_friendship_user_friendships_path(user) , :id => "friend_#{user.id}" , :class => "btn btn-danger" , :remote => true %></td>
				<% else %>
					<td><%= button_to "Invite Friend" , invite_friendship_user_friendships_path(user) , :id => "friend_#{user.id}" , :class => "btn btn-info" , :remote => true %></td>
				<% end %>
			</tr>
 		<% end %>

	</table>

</div>

app/views/users/like.html.erb
<div class="container">
	<h2>My Like</h2>

	<table class="table table-striped">
		<tr>
			<th>Title</th>
			<th>User</th>
		</tr>
		
		<% @likes.each do |like| %>
			<tr>
				<td><%= link_to like.topic.title , topic_path(like.topic) %></td>
				<td><%= link_to like.topic.user.email , user_path(like.topic.user) %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/users/profile.html.erb
<div class="container">
	<h2>Hello! <%= @user.email %></h2>

	<%= link_to "Back To List" , topics_path , :class => "btn btn-primary pull-right" %>
	
	<div class="clearfix"></div>
	
	
	<%= form_for @user , :url => user_path(@user) , :method => :patch do |f| %>
	 	<div class="form-group">
			<%= f.label :avatar , "Avatar: " %>
			<%= f.file_field :avatar %>
		</div>
		<div class="form-group">
		<%= f.label :email , "Email : " %>
		<%= f.text_field :email , :disabled => "disabled" , :class => "form-control" %>
		</div>
		<div class="form-group">
		<%= f.label :nickname , "Nickname : " %>
		<%= f.text_field :nickname , :class => "form-control" %>
		</div>
		<%= f.submit :class => "btn btn-success" %>
	<% end %>

		
	
	<% @topics.each do |t| %>
		<%= form_for t , :url => "" , :method => :patch do |f| %>
			<div class="form-group">
				<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
			</div>
			<div class="form-group">
				<%= f.label :title , "Title : " %>
				<%= f.text_field :title , :class => "form-control" %>
			</div>
				<%= f.label :content , "Content : " %>
				<%= f.text_area :content , :rows => "20" , :class => "form-control" %>
			<div class="form-group">
				<%= f.hidden_field :t_time , :value => Time.now %>
				<%= f.hidden_field :user_id , :value => @user.id %>
			</div>
		<% end %>
	<% end %>

	<% @comments.each  do |c| %>
		<%= form_for c , :url => "" do |f| %>
		<div class="form-group">
			<%= f.label :content , "Content : " %>
			<%= f.text_area :content , :rows => "20" , :class => "form-control" %>
		</div>
			<%= f.hidden_field :user_id , :value => @user.id %>
		<% end %>
	<% end %>

</div>

app/views/users/show.html.erb
<div class="container show">
	
	<h2><%= @user.nickname ? @user.nickname : @user.email %></h2>
	

	<% if current_user != @user %>
		<% if current_user.friends.include?(@user) %>
			<td><%= button_to "Uninvite Friend" , invite_friendship_user_friendships_path(@user) , :id => "friend_#{@user.id}" , :class => "btn btn-danger" , :remote => true %></td>
		<% else %>
			<td><%= button_to "Invite Friend" , invite_friendship_user_friendships_path(@user) , :id => "friend_#{@user.id}" , :class => "btn btn-info" , :remote => true %></td>
		<% end %>
	<% end %>
		
	<% string = '───────────▄▄▄█▄▄█▄▄█▄▄▄ ────────▄▀▀═════════════▀▀▄ ───────█═══════════════════█ ──────█═════════════════════█ ─────█═══▄▄▄▄▄▄▄═══▄▄▄▄▄▄▄═══█ ────█═══█████████═█████████═══█ ────█══██▀────▀█████▀────▀██══█ ───██████──█▀█──███──█▀█──██████ ───██████──▀▀▀──███──▀▀▀──██████ ────█══▀█▄────▄██─██▄────▄█▀══█ ────█════▀█████▀───▀█████▀════█ ────█═════════════════════════█ ────█═════════════════════════█ ────█═══════▀▄▄▄▄▄▄▄▄▄▀═══════█ ────█═════════════════════════█ ───▐▓▓▌═════════════════════▐▓▓▌ ───▐▐▓▓▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▐▓▓▌▌ ───█══▐▓▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄▓▌══█ ──█══▌═▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌═▐══█ ──█══█═▐▓▓▓▓▓▓▄▄▄▄▄▄▄▓▓▓▓▓▓▌═█══█ ──█══█═▐▓▓▓▓▓▓▐██▀██▌▓▓▓▓▓▓▌═█══█ ──█══█═▐▓▓▓▓▓▓▓▀▀▀▀▀▓▓▓▓▓▓▓▌═█══█ ──█══█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█══█ ─▄█══█▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌█══█▄ ─█████▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌─█████ ─██████▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌─██████ ──▀█▀█──▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌───█▀█▀ ─────────▐▓▓▓▓▓▓▌▐▓▓▓▓▓▓▌ ──────────▐▓▓▓▓▌──▐▓▓▓▓▌ ─────────▄████▀────▀████▄ ─────────▀▀▀▀────────▀▀▀▀' %>
	<h1>This guy is so lazy, he did not move his finger once here.</h1>
	
</div>