config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "topics#index"

  resources :users do 
    resources :friendships , :controller => "user_friendships" do
      collection do 
        get :friend_request
        get :friendship
        post :invite_friendship
        post :accept_friendship
        post :refuse_friendship
      end
    end
    resources :favorites , :controller => "user_favorites"
  	resources :topics
    collection do
        get :favorite
        get :like
        get :draft
        patch :update_draft
        get :profile , param: :useremail # XXX
    end
  end

  resources :topics do
  	resources :comments , :controller => "topic_comments"
  	collection do
      get :about 
    end

    member do 
      post :favorite
      post :like
      post :subscribe
      post :create_tag
    end
  end

  namespace :admin do
    resources :topics 
    resources :users
    resources :categories
  end

  namespace :api , path: '' do
    # constraints(host: 'api-example.com') do

    # end
  end


  namespace :api do
    resources :users
    get '*unmatched_route', to: 'base#page_404'
  end

  namespace :test do
    resources :users
    get '*unmatched_route', to: 'base#page_404'
  end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :category_topicships , :dependent => :destroy
	has_many :topics , :through => :category_topicships , :dependent => :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

	before_action :authenticate_user! 
	before_action :authenticate_admin 

	def index
		@cateogries = Category.all
	end

	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(write_category)
		if @category.save
			flash[:notice] = "added successfully"
			redirect_to admin_categories_path
		else
			render "new"
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(write_category)
			flash[:notice] = "update completed"
			redirect_to admin_categories_path
		else
			render "edit"
		end
	end


	protected

	def write_category
		params.require(:category).permit(:name)
	end

	def authenticate_admin
		unless current_user.admin?
		flash[:alert] = "Not allow!"
		redirect_to topics_path
		end
	end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
	<h2>edit</h2>
	
	<%= form_for @category , :url => admin_category_path(@category) , :method => :patch do |f| %>
		<div class="form-group">
			<%= f.label :name , "Name" %>
			<%= f.text_field :name , :class => "form-control" %>
		</div>
		<%= f.submit :class => "btn btn-success" %>
	<% end %>

</div>

	

app/views/admin/categories/index.html.erb
<div class="container">

	<%= link_to "Front stand" , topics_path , :class => "btn btn-danger btn-lg" %>

	<h2>Category</h2>
	
	<%= link_to "Topics" , admin_topics_path , :class => "btn btn-warning pull-right" %>
	<%= link_to "Users" , admin_users_path , :class => "btn btn-warning pull-right" %>
	<%= link_to "New Category" , new_admin_category_path , :class => "btn btn-primary" %>

	<table class="table table-striped">
		<tr>
			<th width=40%>Id</th>
			<th width=40%>Name</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>	

		<% @cateogries.each do |category| %>
			<tr>
				<td><%= category.id %></td>
				<td><%= link_to category.name , admin_category_path(category) %></td>
				<td><%= link_to "Edit" , edit_admin_category_path(category) , :class => "btn btn-warning" %></td>
				<% if category.topics.count == 0 %>
					<td><%= link_to "Delete" , admin_categories_path(category) , :mehtod => :delete , :class => "btn btn-danger" %></td>
				<% else %>
					<td></td>	
				<% end %>
			</tr>
		<% end %>
	</table>
</div>
	

app/views/admin/categories/new.html.erb
<div class="container">
	<h2>New</h2>
	
	<%= form_for @category , :url => admin_categories_path do |f| %>
		<div class="form-group">
			<%= f.label :name , "Name : " %>
			<%= f.text_field :name , :class => "form-control" %>
		</div>
			
		<%= f.submit %>
	<% end %> 

</div>


	
	

app/views/admin/categories/show.html.erb
<div class="container">
	<h2>Show</h2>

	<%= form_for @category , :url => "" do |f| %>
		<div class="form-group">
			<%= f.label :name , "Name : " %>
			<%= f.text_field :name , :disabled => "disabled" , :class => "form-control" %>
		</div>
	<% end %>
</div>