config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "topics#index"

  resources :users do 
    resources :friendships , :controller => "user_friendships" do
      collection do 
        get :friend_request
        get :friendship
        post :invite_friendship
        post :accept_friendship
        post :refuse_friendship
      end
    end
    resources :favorites , :controller => "user_favorites"
  	resources :topics
    collection do
        get :favorite
        get :like
        get :draft
        patch :update_draft
        get :profile , param: :useremail # XXX
    end
  end

  resources :topics do
  	resources :comments , :controller => "topic_comments"
  	collection do
      get :about 
    end

    member do 
      post :favorite
      post :like
      post :subscribe
      post :create_tag
    end
  end

  namespace :admin do
    resources :topics 
    resources :users
    resources :categories
  end

  namespace :api , path: '' do
    # constraints(host: 'api-example.com') do

    # end
  end


  namespace :api do
    resources :users
    get '*unmatched_route', to: 'base#page_404'
  end

  namespace :test do
    resources :users
    get '*unmatched_route', to: 'base#page_404'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar_file_name.rb
class AvatarFileName < ApplicationRecord
    def avatar_file_name
        if avatar_file_name.present?
          avatar_file_name.url
        else
          '/default-avatar.png'
        end
      end
end

app/models/avatar_file_size.rb
class AvatarFileSize < ApplicationRecord
    def avatar_file_size
        if avatar_file_size.present?
          avatar_file_size.url
        else
          '/default-avatar.png'
        end
      end
end

app/models/avatar_updated_at.rb
class AvatarUpdatedAt < ApplicationRecord
    def avatar_updated_at
        if avatar_updated_at.present?
          avatar_updated_at.url
        else
          '/default-avatar.png'
        end
    end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :category_topicships , :dependent => :destroy
	has_many :topics , :through => :category_topicships , :dependent => :destroy
end

app/models/category_topicship.rb
class CategoryTopicship < ApplicationRecord
	belongs_to :category 
	belongs_to :topic 
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates_presence_of :content

	belongs_to :topic , :counter_cache => true
	belongs_to :user 


	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :topic
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :topic

	has_attached_file :image, styles: { medium: "1100x1100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user 
	belongs_to :topic , :counter_cache => true
end

app/models/limit.rb
class Limit < ApplicationRecord
	has_many :topics , :dependent => :destroy
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
	belongs_to :user
	belongs_to :topic
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tag_topicships , :dependent => :destroy
	has_many :tags , :through => :tag_topicships , :dependent => :destroy
end

app/models/tag_topicship.rb
class TagTopicship < ApplicationRecord
	belongs_to :tag
	belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :content , :counter_cache => true

	belongs_to :user
	belongs_to :limit
	has_many :comments , :dependent => :destroy
	has_many :category_topicships , :dependent => :destroy
	has_many :categories , :through => :category_topicships , :dependent => :destroy
	has_many :favorites , :dependent => :destroy
	has_many :favorited_users , :through => :favorites , :source => :user
	has_many :likes , :dependent => :destroy
	has_many :liked_users , :through => :likes , :source => :user
	has_many :subscribes , :dependent => :destroy
	has_many :subscribed_users , :through => :subscribes , :source => :user
	has_many :tag_topicships , :dependent => :destroy
	has_many :tags , :through => :tag_topicships , :dependent => :destroy
	has_many :images , :dependent => :destroy

	delegate :id , :to => :categories , :prefix => true , :allow_nil => true
	
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	def admin?
	self.role == "admin"
	end
	
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

	has_many :topics , :dependent => :destroy
	has_many :comments , :dependent => :destroy
	has_many :favorites , :dependent => :destroy
	has_many :favorited_topics , :through => :favorites , :source => :topic
	has_many :likes , :dependent => :destroy
	has_many :liked_topics , :through => :likes , :source => :topic
	has_many :subscribes , :dependent => :destroy
	has_many :subscribed_topics , :through => :subscribes , :source => :topic
	has_many :friendships , :dependent => :destroy
	has_many :friends, :through => :friendships , :dependent => :destroy
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user


	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  	def get_fb_data
 		j = RestClient.get "https://graph.facebook.com/v2.5/me", :params => { :access_token => self.fb_token, :fields => "id,name,email,picture" }
 		JSON.parse(j)
	end

	def self.from_omniauth(auth)
	     # Case 1: Find existing user by facebook uid
	     user = User.find_by_fb_uid( auth.uid )
	     if user
	        user.fb_token = auth.credentials.token
	        user.avatar_file_name = auth.info.image
	        #user.fb_raw_data = auth
	        user.save!
	       return user
	     end

	     # Case 2: Find existing user by email
	     existing_user = User.find_by_email( auth.info.email )
	     if existing_user
	       existing_user.fb_uid = auth.uid
	       existing_user.fb_token = auth.credentials.token
	       existing_user.avatar_file_name = auth.info.image
	       #existing_user.fb_raw_data = auth
	       existing_user.save!
	       return existing_user
	     end

	     # Case 3: Create new password
	     user = User.new
	     user.fb_uid = auth.uid
	     user.fb_token = auth.credentials.token
	     user.avatar_file_name = auth.info.image
	     user.email = auth.info.email
	     user.password = Devise.friendly_token[0,20]
	     #user.fb_raw_data = auth
	     user.save!
	     return user
	end
    # def avatar_content_type
    #     if avatar_content_type.present?
    #       avatar_content_type.url
    #     else
    #       '/default-avatar.png'
    #     end
	# end
	# def avatar_file_name
    #     if avatar_file_name.present?
    #       avatar_file_name.url
    #     else
    #       '/default-avatar.png'
    #     end
    # end
	# def avatar_file_size
    #     if avatar_file_size.present?
    #       avatar_file_size.url
    #     else
    #       '/default-avatar.png'
    #     end
	# end
	# def avatar_updated_at
    #     if avatar_updated_at.present?
    #       avatar_updated_at.url
    #     else
    #       '/default-avatar.png'
    #     end
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>

	
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class="container">
		<%# <div class="fb-like" data-href="http://www.localhost:3000/" data-width="20px" data-layout="standard" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div> %>
		<div class="pull-right">
			<% if current_user %>
 				<% if current_user.friendships.count < current_user.inverse_friendships.count %>
					<%= link_to "Friend Request" , friend_request_user_friendships_path(current_user) , :class => "btn btn-success" %>
 				<% end %>

				<% if current_user.fb_uid %>
					<%= image_tag current_user.avatar_file_name %>
				<% else %>
					 <%# <%= image_tag current_user.avatar_file_name.url(:thumb)%>
				<% end %>
				<div class="btn-group">
				  <%= link_to current_user.email , profile_users_path(:useremail => current_user.email) , :type => "button" , :class => "btn btn-info" %>
				  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    <span class="caret"></span>
				    <span class="sr-only">Toggle Dropdown</span>
				  </button>
				  <ul class="dropdown-menu">
			  		<li><%= link_to "My bookmarks" , favorite_users_path %></li>
					<li><%= link_to "My draft" , draft_users_path %></li>
					<li><%= link_to "My like" , like_users_path %></li>
					<li><%= link_to "my good friend" , friendship_user_friendships_path(current_user) %></li>
					<li><%= link_to "Users" , users_path %></li>
					<li role="separator" class="divider"></li>
					<li><%= link_to('change Password', edit_registration_path(:user) ) %></li>
				    <li><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></li>
					

			    </ul>
				</div>
		    <% else %>
				<%= link_to('registered', new_registration_path(:user)) %> |
			    <%= link_to('Sign in', new_session_path(:user)) %> |
			    <%= link_to "Sign in Facebook", user_facebook_omniauth_authorize_path %>

			<% end %>    
		</div>
	</div>


	<div class="container">
		<% if flash[:notice].present? %>
			<div class="alert alert-success" role="alert">
				<%= flash[:notice] %>
			</div>
		<% end %>


		<% if flash[:alert].present? %>
			<div class="alert alert-danger" role="alert">
				<%= flash[:alert] %>
			</div> 
		<% end %>
	</div>

    <%= yield %>
    
  </body>
</html>

<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.8&appId=1852697651643312";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>